<?php
require_once '../../config.php'; require_once '../../includes/helpers.php'; require_once '../../includes/finance.php';
$clients=get_data('clientes'); $names=[]; foreach($clients as $c)$names[$c['id']]=$c['nombre'];
$filters=['cliente_id'=>$_GET['cliente_id']??'','estado'=>$_GET['estado']??'','desde'=>$_GET['desde']??'','hasta'=>$_GET['hasta']??''];
$rows=[]; foreach(get_data('ventas') as $sale){$f=sale_financials($sale); if($filters['cliente_id']!==''&&(string)$sale['cliente_id']!==$filters['cliente_id'])continue;if($filters['estado']!==''&&$f['estado']!==$filters['estado'])continue;$due=$sale['fecha_vencimiento']??'';if($filters['desde']!==''&&($due===''||$due<$filters['desde']))continue;if($filters['hasta']!==''&&($due===''||$due>$filters['hasta']))continue;$rows[]=[$sale,$f];}
include '../../includes/header.php';
?>
<div class="page-heading d-flex justify-content-between align-items-end mb-4"><div><span class="page-eyebrow">Tesorería</span><h1 class="h3 mb-1">Cuentas por cobrar</h1><p class="text-muted mb-0">Controla vencimientos, pagos recibidos y saldos de clientes.</p></div><a class="btn btn-outline-success" href="<?php echo url('actions/exportar_csv.php?reporte=cobros&'.http_build_query($filters)); ?>"><i class="bi bi-file-earmark-spreadsheet me-1"></i>Exportar CSV</a></div>
<form class="card card-body mb-4 row g-3 flex-row" method="get"><div class="col-md-3"><label class="form-label">Cliente</label><select class="form-select" name="cliente_id"><option value="">Todos</option><?php foreach($clients as $c): ?><option value="<?php echo $c['id']; ?>" <?php echo $filters['cliente_id']==$c['id']?'selected':''; ?>><?php echo htmlspecialchars($c['nombre']); ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach(['Pendiente','Parcialmente pagado','Pagado','Vencido'] as $s): ?><option <?php echo $filters['estado']===$s?'selected':''; ?>><?php echo $s; ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Vence desde</label><input class="form-control" type="date" name="desde" value="<?php echo htmlspecialchars($filters['desde']); ?>"></div><div class="col-md-2"><label class="form-label">Vence hasta</label><input class="form-control" type="date" name="hasta" value="<?php echo htmlspecialchars($filters['hasta']); ?>"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Filtrar</button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Venta</th><th>Cliente</th><th>Vencimiento</th><th>Estado</th><th class="text-end">Cargo</th><th class="text-end">Cobrado</th><th class="text-end">Saldo</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7" class="text-center py-5 text-muted">No hay cuentas que coincidan con los filtros.</td></tr><?php endif; ?><?php foreach($rows as [$s,$f]): ?><tr><td><a href="<?php echo url('pages/ventas/detalle.php?id='.$s['id']); ?>"><?php echo htmlspecialchars($s['serie'].'-'.$s['numero']); ?></a></td><td><?php echo htmlspecialchars($names[$s['cliente_id']]??'Cliente no disponible'); ?></td><td><?php echo htmlspecialchars($s['fecha_vencimiento']??'Sin fecha'); ?></td><td><span class="badge bg-<?php echo $f['estado']==='Pagado'?'success':($f['estado']==='Vencido'?'danger':'warning text-dark'); ?>"><?php echo $f['estado']; ?></span></td><td class="text-end"><?php echo format_money($f['cargo']); ?></td><td class="text-end"><?php echo format_money($f['pagado']); ?></td><td class="text-end fw-bold"><?php echo format_money($f['saldo']); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include '../../includes/footer.php'; ?>
