<?php
require_once '../../config.php'; require_once '../../includes/helpers.php';
$showFiles=true; include '../../includes/header.php';
?>
<div class="page-heading d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span class="page-eyebrow">SUNAT / Facturación electrónica</span><h1 class="h3 mb-1">Documentos electrónicos</h1><p class="text-muted mb-0">Comprobantes de la empresa activa preparados para una futura integración.</p></div><a class="btn btn-outline-secondary" href="<?php echo url('pages/sunat/index.php'); ?>"><i class="bi bi-arrow-left me-1"></i>Módulo SUNAT</a></div>
<div class="sunat-prototype-note mb-4"><i class="bi bi-info-circle"></i><span><strong>Vista demostrativa.</strong> Todos los comprobantes aparecen como “No enviado”; no existe comunicación con SUNAT.</span></div>
<section class="card mb-4"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><div><span class="chart-kicker">Empresa activa</span><h2 class="h6 mb-0">Comprobantes registrados</h2></div><span class="sunat-development">En desarrollo</span></div><?php include '../../includes/sunat_documents_table.php'; ?></section>
<section class="card mb-4"><div class="card-header"><div><span class="chart-kicker">Acciones futuras</span><h2 class="h6 mb-0">Procesamiento electrónico</h2></div></div><div class="card-body"><div class="sunat-disabled-actions"><?php foreach([['filetype-xml','Generar XML'],['pen','Firmar XML'],['send','Enviar a SUNAT'],['inbox','Consultar CDR'],['download','Descargar XML'],['download','Descargar CDR']] as $action): ?><button disabled><i class="bi bi-<?php echo $action[0]; ?>"></i><span><?php echo $action[1]; ?></span><small>Disponible en integración real</small></button><?php endforeach; ?></div></div></section>
<section class="card mb-4"><div class="card-header"><div><span class="chart-kicker">Referencia conceptual</span><h2 class="h6 mb-0">Estados futuros del documento electrónico</h2></div></div><div class="card-body"><div class="sunat-state-list"><?php foreach([['Pendiente','Aún no inicia el procesamiento.'],['XML generado','Existe la representación electrónica.'],['Firmado','El XML cuenta con firma digital.'],['Enviado','Fue remitido al servicio tributario.'],['Aceptado','La respuesta confirma la aceptación.'],['Observado','Requiere revisar observaciones.'],['Rechazado','La respuesta no acepta el documento.'],['Anulado','El documento fue anulado mediante el proceso correspondiente.']] as $state): ?><div><strong><?php echo $state[0]; ?></strong><span><?php echo $state[1]; ?></span></div><?php endforeach; ?></div><p class="small text-muted mt-3 mb-0">Estos estados son únicamente explicativos y no están asignados a los comprobantes del prototipo.</p></div></section>
<?php include '../../includes/footer.php'; ?>

