<?php
require_once __DIR__.'/kardex.php'; require_once __DIR__.'/xlsx.php';
function kardex_export_filters($input){$filters=[];foreach(['producto_id','almacen_id','tipo_operacion','desde','hasta','venta_id']as$key){$value=$input[$key]??'';if(!is_string($value))throw new InvalidArgumentException('Filtro inválido: '.$key);$filters[$key]=trim($value);}if(isset($input['empresa_id'])&&(string)$input['empresa_id']!==(string)($_SESSION['empresa_id']??''))throw new InvalidArgumentException('La empresa activa no coincide con la exportación.');return $filters;}
function kardex_export_context($input){
 $filters=kardex_export_filters($input);$rows=filter_kardex(get_data('kardex'),$filters);if(!$rows)throw new InvalidArgumentException('No existen movimientos para exportar con los filtros seleccionados.');
 $products=get_data('productos');$warehouses=get_data('almacenes');$productMap=array_column($products,null,'id');$warehouseMap=array_column($warehouses,null,'id');$company=null;foreach(read_data('empresas')as$row)if((string)$row['id']===(string)$_SESSION['empresa_id']){$company=$row;break;}if(!$company)throw new InvalidArgumentException('Empresa no disponible.');
 $product=$filters['producto_id']!==''?owned_record('productos',$filters['producto_id']):null;$warehouse=$filters['almacen_id']!==''?owned_record('almacenes',$filters['almacen_id']):null;
 $summary=['entrada_cantidad'=>0.0,'entrada_valor'=>0.0,'salida_cantidad'=>0.0,'salida_valor'=>0.0];foreach($rows as$row)foreach($summary as$key=>$value)$summary[$key]+=(float)($row[$key]??0);
 $current=null;if($product&&$warehouse)foreach(get_data('inventario')as$row)if((string)$row['producto_id']===(string)$product['id']&&(string)$row['almacen_id']===(string)$warehouse['id']){$current=$row;break;}
 return compact('filters','rows','productMap','warehouseMap','company','product','warehouse','summary','current');
}
function kardex_export_filename($context){$parts=['kardex'];if($context['product'])$parts[]=$context['product']['sku']??$context['product']['nombre'];if($context['warehouse'])$parts[]=$context['warehouse']['nombre'];if(!$context['product']&&!$context['warehouse'])$parts[]=$context['company']['razon_social'];$name=implode('_',$parts).'_'.date('Y-m-d');$name=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$name)?:$name;$name=preg_replace('/[^A-Za-z0-9_-]+/','_',$name);return trim($name,'_').'.xlsx';}
function write_kardex_xlsx($context,$path){
 $rows=[];$rows[]='<row r="1" ht="26">'.xlsx_cell(1,1,'KARDEX VALORIZADO',1).'</row>'; $merges=['A1:O1'];
 $info=[['Empresa',$context['company']['razon_social']],['RUC',$context['company']['ruc']??''],['Producto',$context['product']?($context['product']['sku'].' · '.$context['product']['nombre']):'Todos'],['Almacén',$context['warehouse']['nombre']??'Todos'],['Periodo',($context['filters']['desde']?:'Sin inicio').' al '.($context['filters']['hasta']?:'Sin fin')],['Fecha de exportación',date('d/m/Y H:i')]];
 $r=2;foreach($info as[$label,$value]){$rows[]='<row r="'.$r.'">'.xlsx_cell(1,$r,$label,2).xlsx_cell(2,$r,$value).'</row>';$merges[]='B'.$r.':O'.$r;$r++;}
 $rows[]='<row r="9">'.xlsx_cell(1,9,'DATOS DEL MOVIMIENTO',3).xlsx_cell(7,9,'ENTRADAS',3).xlsx_cell(10,9,'SALIDAS',3).xlsx_cell(13,9,'SALDO HISTÓRICO',3).'</row>';foreach(['A9:F9','G9:I9','J9:L9','M9:O9']as$m)$merges[]=$m;
 $headers=['Fecha','Operación','Documento','Producto','Código','Almacén','Cantidad entrada','Costo unitario entrada','Valor entrada','Cantidad salida','Costo unitario salida','Valor salida','Cantidad saldo','CPP','Valor saldo'];$cells='';foreach($headers as$i=>$header)$cells.=xlsx_cell($i+1,10,$header,4);$rows[]='<row r="10" ht="30">'.$cells.'</row>';
 $r=11;foreach($context['rows']as$movement){$product=$context['productMap'][$movement['producto_id']]??[];$warehouse=$context['warehouseMap'][$movement['almacen_id']]??[];$values=[substr($movement['fecha'],0,10),$movement['tipo_operacion']??'',$movement['documento']??'',$product['nombre']??'Producto no disponible',$product['sku']??'S/C',$warehouse['nombre']??'Almacén no disponible'];$cells='';foreach($values as$i=>$value)$cells.=xlsx_cell($i+1,$r,$value,7);foreach([['entrada_cantidad',5],['entrada_costo',6],['entrada_valor',6],['salida_cantidad',5],['salida_costo',6],['salida_valor',6],['saldo_cantidad',5],['cpp',6],['saldo_valor',6]]as$i=>$spec)$cells.=xlsx_cell($i+7,$r,(float)($movement[$spec[0]]??0),$spec[1],true);$rows[]='<row r="'.$r.'">'.$cells.'</row>';$r++;}
 $summaryRow=$r+1;$rows[]='<row r="'.$summaryRow.'">'.xlsx_cell(1,$summaryRow,'RESUMEN VISIBLE',2).xlsx_cell(2,$summaryRow,'Movimientos: '.count($context['rows'])).xlsx_cell(7,$summaryRow,$context['summary']['entrada_cantidad'],5,true).xlsx_cell(9,$summaryRow,$context['summary']['entrada_valor'],6,true).xlsx_cell(10,$summaryRow,$context['summary']['salida_cantidad'],5,true).xlsx_cell(12,$summaryRow,$context['summary']['salida_valor'],6,true).'</row>';$merges[]='B'.$summaryRow.':F'.$summaryRow;
 if($context['product']&&$context['warehouse']&&$context['current']){$r=$summaryRow+1;$current=$context['current'];$rows[]='<row r="'.$r.'">'.xlsx_cell(1,$r,'SALDO ACTUAL',2).xlsx_cell(2,$r,$current['stock_actual'],5,true).xlsx_cell(3,$r,'CPP').xlsx_cell(4,$r,$current['cpp'],6,true).xlsx_cell(5,$r,'Valor').xlsx_cell(6,$r,$current['valor_inventario'],6,true).'</row>';}
 $lastData=10+count($context['rows']);$columns=[14,20,24,28,14,22,14,17,16,14,17,16,14,14,16];$cols='';foreach($columns as$i=>$width)$cols.='<col min="'.($i+1).'" max="'.($i+1).'" width="'.$width.'" customWidth="1"/>';
 $sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="10" topLeftCell="A11" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'.$cols.'</cols><sheetData>'.implode('',$rows).'</sheetData><autoFilter ref="A10:O'.$lastData.'"/><mergeCells count="'.count($merges).'">'.implode('',array_map(fn($m)=>'<mergeCell ref="'.$m.'"/>',$merges)).'</mergeCells></worksheet>';
 return xlsx_write_file($path,$sheet,'Kardex Valorizado');
}
