<?php
$financial = sale_financials($venta);
$payments = array_values(array_filter(get_data('pagos'), fn($row) => $row['venta_id'] == $venta['id']));
?>
<div class="alert <?php echo ($venta['estado_documento'] ?? 'Vigente') === 'Anulada' ? 'alert-danger' : 'alert-info'; ?> mt-4">
 Documento: <strong><?php echo htmlspecialchars($venta['estado_documento'] ?? 'Vigente'); ?></strong> · Entrega: <strong><?php echo htmlspecialchars(dispatch_status($venta)); ?></strong> · Cobro: <strong><?php echo htmlspecialchars($financial['estado']); ?></strong>
</div>
<div class="row g-4 mt-1">
 <div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="h5 mb-0">Cobros y saldo</h3></div><div class="card-body">
  <dl class="row"><dt class="col-6">Cargo vigente</dt><dd class="col-6 text-end"><?php echo format_money($financial['cargo']); ?></dd><dt class="col-6">Cobrado</dt><dd class="col-6 text-end"><?php echo format_money($financial['pagado']); ?></dd><dt class="col-6">Saldo pendiente</dt><dd class="col-6 text-end fw-bold"><?php echo format_money($financial['saldo']); ?></dd><dt class="col-6">Saldo a favor</dt><dd class="col-6 text-end fw-bold text-warning"><?php echo format_money($financial['saldo_favor']); ?></dd></dl>
  <?php if($financial['saldo']>0 && ($venta['estado_documento']??'Vigente')!=='Anulada'): ?><form action="<?php echo url('actions/registrar_pago.php'); ?>" method="post" class="row g-2"><div class="form-errors alert alert-danger d-none col-12"></div><?php echo form_context(); ?><input type="hidden" name="venta_id" value="<?php echo (int)$venta['id']; ?>"><div class="col-sm-4"><label class="form-label">Fecha *</label><input class="form-control" type="date" name="fecha" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-sm-4"><label class="form-label">Importe *</label><input class="form-control" type="number" name="importe" min="0.01" step="0.01" max="<?php echo $financial['saldo']; ?>" required></div><div class="col-sm-4"><label class="form-label">Medio *</label><select class="form-select" name="medio" required><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Yape/Plin</option><option>Otro</option></select></div><div class="col-8"><label class="form-label">Referencia</label><input class="form-control" name="referencia"></div><div class="col-4 d-flex align-items-end"><button class="btn btn-success w-100" type="submit">Registrar</button></div></form><?php endif; ?>
  <?php if($payments): ?><hr><ul class="list-group list-group-flush"><?php foreach($payments as $p): ?><li class="list-group-item d-flex justify-content-between"><span><?php echo htmlspecialchars($p['fecha'].' · '.$p['medio'].' · '.$p['referencia']); ?></span><strong><?php echo format_money($p['importe']); ?></strong></li><?php endforeach; ?></ul><?php endif; ?>
  <?php if($financial['saldo_favor']>0): ?><hr><h4 class="h6">Registrar reembolso</h4><form action="<?php echo url('actions/registrar_reembolso.php'); ?>" method="post" class="row g-2"><div class="form-errors alert alert-danger d-none col-12"></div><?php echo form_context(); ?><input type="hidden" name="venta_id" value="<?php echo (int)$venta['id']; ?>"><div class="col-sm-4"><input aria-label="Fecha" class="form-control" type="date" name="fecha" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-sm-4"><input aria-label="Importe" class="form-control" type="number" name="importe" min="0.01" step="0.01" max="<?php echo $financial['saldo_favor']; ?>" required></div><div class="col-sm-4"><input aria-label="Medio" class="form-control" name="medio" placeholder="Medio" required></div><div class="col-8"><input aria-label="Referencia" class="form-control" name="referencia" placeholder="Referencia"></div><div class="col-4"><button class="btn btn-warning w-100">Reembolsar</button></div></form><?php endif; ?>
 </div></div></div>
 <div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="h5 mb-0">Devolución y anulación</h3></div><div class="card-body">
  <p class="small text-muted">La devolución reingresa mercadería al almacén usando el costo exacto de los despachos originales.</p>
  <?php $canReturn=false; foreach($venta['detalles'] as $i=>$line) if(delivered_quantity($venta,$line)-returned_quantity($venta,$i)>0)$canReturn=true; ?>
  <?php if($canReturn): ?><form action="<?php echo url('actions/procesar_devolucion.php'); ?>" method="post"><div class="form-errors alert alert-danger d-none"></div><?php echo form_context(); ?><input type="hidden" name="venta_id" value="<?php echo (int)$venta['id']; ?>"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Producto</th><th>Disponible</th><th>Devolver</th></tr></thead><tbody><?php foreach($venta['detalles'] as $i=>$line): $available=round(delivered_quantity($venta,$line)-returned_quantity($venta,$i),3); ?><tr><td><?php echo htmlspecialchars($getProdName($line['producto_id'])); ?></td><td><?php echo $available.' '.htmlspecialchars($line['unidad_medida']??'UN'); ?></td><td><input class="form-control" type="number" name="cantidades[]" value="0" min="0" max="<?php echo $available; ?>" step="<?php echo quantity_step($line['unidad_medida']??'UN'); ?>"></td></tr><?php endforeach; ?></tbody></table></div><div class="row g-2"><div class="col-sm-4"><label class="form-label">Fecha *</label><input class="form-control" type="date" name="fecha" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-sm-8"><label class="form-label">Motivo *</label><input class="form-control" name="motivo" required></div></div><button class="btn btn-outline-danger mt-3">Registrar devolución</button></form><?php else: ?><p class="text-muted">No quedan cantidades entregadas por devolver.</p><?php endif; ?>
  <?php if(($venta['estado_documento']??'Vigente')!=='Anulada'): ?><hr><form action="<?php echo url('actions/anular_venta.php'); ?>" method="post"><div class="form-errors alert alert-danger d-none"></div><?php echo form_context(); ?><input type="hidden" name="venta_id" value="<?php echo (int)$venta['id']; ?>"><div class="row g-2"><div class="col-sm-4"><input aria-label="Fecha de anulación" class="form-control" type="date" name="fecha" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-sm-8"><input aria-label="Motivo" class="form-control" name="motivo" placeholder="Motivo de anulación" required></div></div><p class="small text-danger mt-2">Anular cancela el documento y lo pendiente; no repone entregas. Registra el retorno físico por separado.</p><button class="btn btn-danger">Anular documento</button></form><?php endif; ?>
 </div></div></div>
</div>
